spring:
  profiles:
    active: local

  application:
    name: healthcare-hackathon

  # Spring Security 완전 비활성화 (해커톤용)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP 설정
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create  # 해커톤용 (처음엔 create, 이후 update)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL8Dialect 대신 사용
        default_batch_fetch_size: 100
    open-in-view: false

  # Jackson 설정
  jackson:
    # property-naming-strategy: SNAKE_CASE  # 이 줄을 주석처리 또는 삭제!
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hackathon.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: false

# 서버 설정
server:
  port: 8082
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# JWT 설정
jwt:
  secret: hackathon2025secretkeyhackathon2025secretkey
  expiration: 86400000

# CORS 설정
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:19006
    - http://localhost:8081
    - http://10.0.2.2:8082  # Android 에뮬레이터
    - http://10.10.180.66:8082  # 개발 PC
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
    - Accept
    - Origin
  exposed-headers:
    - Authorization

# 로깅 설정
logging:
  level:
    com.hackathon: DEBUG
    com.hackathon.mapper: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  security:
    enabled: false  # Actuator 보안 비활성화

# Tilko API 설정 추가
tilko:
  api:
    host: https://dev.tilko.net
    key: ${TILKO_API_KEY:your-tilko-api-key-here}

# 모델명 :claude-3-sonnet-20240229
claude:
  api:
    url: https://api.anthropic.com/v1/messages
    key: ${CLAUDE_API_KEY:your-claude-api-key-here}
    model: claude-3-sonnet-20240229
    max-tokens: 1000

# gpt api 설정
#chatgpt:
#  api:
#    url: https://api.openai.com/v1/chat/completions
#    key: ${CHATGPT_API_KEY:your-chatgpt-api-key-here}
#    model: gpt-4o-mini
#    max-tokens: 1000